#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

GREEN='\033[0;32m'
LIGHT_BLUE='\033[1;34m'
NO_COLOR='\033[0m'

echo "${LIGHT_BLUE}!${NO_COLOR} Formatting Staged Files"
bun lint-staged ${staged}

echo "${GREEN} Formatted" ${staged}
echo "${GREEN}✔${NO_COLOR} Done Formatting"

echo "${LIGHT_BLUE}!${NO_COLOR} Checking for Circlar Dependency"
bun run cruise src || exit $

echo "${GREEN}✔${NO_COLOR} Done Running Pre-commit\n"